"""Explicit, reviewed language rows for meetings and profile recovery UI."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
CODES='en de es fr it pt el ru sr pl sl sk cs bg ro mk hu sv nb fi da nl is'.split()
OUT={c:{} for c in CODES}
def batch(keys, rows):
 keys=keys.split('|');assert set(rows)==set(CODES)-{'ru'}
 for c in CODES:
  vals=keys if c=='ru' else rows[c].split('|')
  assert len(vals)==len(keys),(c,len(vals),len(keys))
  OUT[c].update(zip(keys,vals))
batch('Вернуться в чат|Встреча недоступна|Вы были исключены из встречи|Вы не являетесь участником встречи|Вы приняли приглашение на встречу|Вы уверены, что хотите исключить этого пользователя?|Исключить участника|Написать организатору|Обо встрече|Организатор|По выбранным параметрам пока никого нет|Пока на вашей странице не было гостей.|Принять приглашение на встречу|Уведомления включены|Уведомления выключены|Удалить встречу?|Укажите название, страну и регион|Выберите страну и регион.',{
'en':'Return to chat|Meeting unavailable|You were removed from this meeting|You are not a participant in this meeting|You accepted the meeting invitation|Are you sure you want to remove this participant?|Remove participant|Message the organizer|About the meeting|Organizer|No one matches these filters yet|No one has visited your profile yet.|Accept meeting invitation|Notifications on|Notifications off|Delete meeting?|Enter a title, country and region|Select a country and region.',
'de':'Zurück zum Chat|Treffen nicht verfügbar|Sie wurden aus diesem Treffen ausgeschlossen|Sie nehmen an diesem Treffen nicht teil|Sie haben die Einladung zum Treffen angenommen|Möchten Sie diese Person wirklich ausschließen?|Teilnehmer ausschließen|Organisator anschreiben|Über das Treffen|Organisator|Noch keine Personen für diese Filter|Ihr Profil wurde noch nicht besucht.|Einladung zum Treffen annehmen|Benachrichtigungen aktiviert|Benachrichtigungen deaktiviert|Treffen löschen?|Titel, Land und Region angeben|Wählen Sie Land und Region.',
'es':'Volver al chat|Encuentro no disponible|Se te ha excluido de este encuentro|No participas en este encuentro|Has aceptado la invitación al encuentro|¿Seguro que quieres excluir a esta persona?|Excluir participante|Escribir al organizador|Acerca del encuentro|Organizador|Aún no hay personas que coincidan con estos filtros|Todavía no han visitado tu perfil.|Aceptar invitación al encuentro|Notificaciones activadas|Notificaciones desactivadas|¿Eliminar encuentro?|Indica un título, un país y una región|Selecciona un país y una región.',
'fr':'Revenir au chat|Rencontre indisponible|Vous avez été exclu de cette rencontre|Vous ne participez pas à cette rencontre|Vous avez accepté l’invitation à la rencontre|Voulez-vous vraiment exclure cette personne ?|Exclure le participant|Écrire à l’organisateur|À propos de la rencontre|Organisateur|Aucun profil ne correspond encore à ces filtres|Votre profil n’a pas encore été visité.|Accepter l’invitation à la rencontre|Notifications activées|Notifications désactivées|Supprimer la rencontre ?|Indiquez un titre, un pays et une région|Sélectionnez un pays et une région.',
'it':'Torna alla chat|Incontro non disponibile|Sei stato escluso da questo incontro|Non partecipi a questo incontro|Hai accettato l’invito all’incontro|Vuoi davvero escludere questa persona?|Escludi partecipante|Scrivi all’organizzatore|Informazioni sull’incontro|Organizzatore|Nessuno corrisponde ancora a questi filtri|Nessuno ha ancora visitato il tuo profilo.|Accetta l’invito all’incontro|Notifiche attivate|Notifiche disattivate|Eliminare l’incontro?|Indica un titolo, un paese e una regione|Seleziona un paese e una regione.',
'pt':'Voltar à conversa|Encontro indisponível|Você foi removido deste encontro|Você não participa deste encontro|Você aceitou o convite para o encontro|Tem certeza de que deseja remover esta pessoa?|Remover participante|Escrever ao organizador|Sobre o encontro|Organizador|Ainda não há pessoas com estes filtros|Seu perfil ainda não recebeu visitas.|Aceitar convite para o encontro|Notificações ativadas|Notificações desativadas|Excluir encontro?|Informe um título, país e região|Selecione um país e uma região.',
'el':'Επιστροφή στη συνομιλία|Η συνάντηση δεν είναι διαθέσιμη|Απομακρυνθήκατε από αυτή τη συνάντηση|Δεν συμμετέχετε σε αυτή τη συνάντηση|Αποδεχτήκατε την πρόσκληση στη συνάντηση|Θέλετε σίγουρα να απομακρύνετε αυτό το άτομο;|Απομάκρυνση συμμετέχοντα|Μήνυμα στον διοργανωτή|Σχετικά με τη συνάντηση|Διοργανωτής|Δεν βρέθηκαν ακόμη άτομα με αυτά τα φίλτρα|Κανείς δεν έχει επισκεφτεί ακόμη το προφίλ σας.|Αποδοχή πρόσκλησης στη συνάντηση|Ειδοποιήσεις ενεργές|Ειδοποιήσεις ανενεργές|Διαγραφή συνάντησης;|Συμπληρώστε τίτλο, χώρα και περιοχή|Επιλέξτε χώρα και περιοχή.',
'sr':'Назад на разговор|Сусрет није доступан|Уклоњени сте са овог сусрета|Нисте учесник овог сусрета|Прихватили сте позив на сусрет|Да ли заиста желите да уклоните овог учесника?|Уклони учесника|Пиши организатору|О сусрету|Организатор|Још нема особа које одговарају овим филтерима|Ваш профил још нико није посетио.|Прихвати позив на сусрет|Обавештења су укључена|Обавештења су искључена|Обрисати сусрет?|Унесите назив, државу и регион|Изаберите државу и регион.',
'pl':'Wróć do czatu|Spotkanie niedostępne|Usunięto Cię z tego spotkania|Nie uczestniczysz w tym spotkaniu|Przyjęto zaproszenie na spotkanie|Czy na pewno chcesz usunąć tę osobę?|Usuń uczestnika|Napisz do organizatora|O spotkaniu|Organizator|Nikt jeszcze nie pasuje do tych filtrów|Nikt jeszcze nie odwiedził Twojego profilu.|Przyjmij zaproszenie na spotkanie|Powiadomienia włączone|Powiadomienia wyłączone|Usunąć spotkanie?|Podaj nazwę, kraj i region|Wybierz kraj i region.',
'sl':'Nazaj v klepet|Srečanje ni na voljo|Odstranjeni ste bili s tega srečanja|Niste udeleženec tega srečanja|Sprejeli ste povabilo na srečanje|Ali res želite odstraniti to osebo?|Odstrani udeleženca|Piši organizatorju|O srečanju|Organizator|Tem filtrom še nihče ne ustreza|Vašega profila še nihče ni obiskal.|Sprejmi povabilo na srečanje|Obvestila so vključena|Obvestila so izključena|Izbrisati srečanje?|Vnesite naslov, državo in regijo|Izberite državo in regijo.',
'sk':'Späť do chatu|Stretnutie nie je dostupné|Boli ste vylúčení z tohto stretnutia|Nie ste účastníkom tohto stretnutia|Prijali ste pozvanie na stretnutie|Naozaj chcete odstrániť túto osobu?|Odstrániť účastníka|Napísať organizátorovi|O stretnutí|Organizátor|Týmto filtrom zatiaľ nikto nezodpovedá|Váš profil zatiaľ nikto nenavštívil.|Prijať pozvanie na stretnutie|Upozornenia zapnuté|Upozornenia vypnuté|Odstrániť stretnutie?|Zadajte názov, krajinu a región|Vyberte krajinu a región.',
'cs':'Zpět do chatu|Setkání není dostupné|Byli jste vyloučeni z tohoto setkání|Nejste účastníkem tohoto setkání|Přijali jste pozvání na setkání|Opravdu chcete odebrat tuto osobu?|Odebrat účastníka|Napsat organizátorovi|O setkání|Organizátor|Těmto filtrům zatím nikdo neodpovídá|Váš profil zatím nikdo nenavštívil.|Přijmout pozvání na setkání|Oznámení zapnuta|Oznámení vypnuta|Smazat setkání?|Zadejte název, zemi a region|Vyberte zemi a region.',
'bg':'Обратно в чата|Срещата е недостъпна|Отстранени сте от тази среща|Не сте участник в тази среща|Приехте поканата за срещата|Сигурни ли сте, че искате да отстраните този човек?|Отстрани участника|Пиши на организатора|За срещата|Организатор|Все още няма хора според тези филтри|Все още никой не е посетил профила ви.|Приеми поканата за срещата|Известията са включени|Известията са изключени|Изтриване на срещата?|Въведете име, държава и регион|Изберете държава и регион.',
'ro':'Înapoi la chat|Întâlnire indisponibilă|Ai fost exclus de la această întâlnire|Nu participi la această întâlnire|Ai acceptat invitația la întâlnire|Sigur vrei să excluzi această persoană?|Exclude participantul|Scrie organizatorului|Despre întâlnire|Organizator|Încă nu există persoane care corespund acestor filtre|Nimeni nu ți-a vizitat încă profilul.|Acceptă invitația la întâlnire|Notificări activate|Notificări dezactivate|Ștergi întâlnirea?|Introdu un titlu, țara și regiunea|Selectează țara și regiunea.',
'mk':'Назад во разговорот|Средбата не е достапна|Отстранети сте од оваа средба|Не сте учесник на оваа средба|Ја прифативте поканата за средбата|Дали навистина сакате да го отстраните ова лице?|Отстрани учесник|Пиши му на организаторот|За средбата|Организатор|Сè уште нема лица што одговараат на овие филтри|Вашиот профил сè уште нема посетители.|Прифати ја поканата за средбата|Известувањата се вклучени|Известувањата се исклучени|Да се избрише средбата?|Внесете наслов, држава и регион|Изберете држава и регион.',
'hu':'Vissza a beszélgetéshez|A találkozó nem érhető el|Eltávolították erről a találkozóról|Nem vesz részt ezen a találkozón|Elfogadta a meghívást a találkozóra|Biztosan eltávolítja ezt a személyt?|Résztvevő eltávolítása|Üzenet a szervezőnek|A találkozóról|Szervező|Még senki sem felel meg ezeknek a szűrőknek|Még senki sem látogatta meg a profilját.|Meghívás elfogadása|Értesítések bekapcsolva|Értesítések kikapcsolva|Törli a találkozót?|Adja meg a címet, az országot és a régiót|Válasszon országot és régiót.',
'sv':'Tillbaka till chatten|Träffen är inte tillgänglig|Du har tagits bort från den här träffen|Du deltar inte i den här träffen|Du har accepterat inbjudan till träffen|Vill du verkligen ta bort den här personen?|Ta bort deltagare|Skriv till arrangören|Om träffen|Arrangör|Ingen matchar dessa filter ännu|Ingen har besökt din profil ännu.|Acceptera inbjudan till träffen|Aviseringar på|Aviseringar av|Ta bort träffen?|Ange namn, land och region|Välj land och region.',
'nb':'Tilbake til chatten|Treffet er ikke tilgjengelig|Du er fjernet fra dette treffet|Du deltar ikke på dette treffet|Du har godtatt invitasjonen til treffet|Vil du virkelig fjerne denne personen?|Fjern deltaker|Skriv til arrangøren|Om treffet|Arrangør|Ingen passer disse filtrene ennå|Ingen har besøkt profilen din ennå.|Godta invitasjon til treffet|Varsler på|Varsler av|Slette treffet?|Oppgi navn, land og region|Velg land og region.',
'fi':'Takaisin keskusteluun|Tapaaminen ei ole saatavilla|Sinut poistettiin tästä tapaamisesta|Et osallistu tähän tapaamiseen|Hyväksyit kutsun tapaamiseen|Haluatko varmasti poistaa tämän henkilön?|Poista osallistuja|Kirjoita järjestäjälle|Tietoa tapaamisesta|Järjestäjä|Kukaan ei vielä vastaa näitä suodattimia|Profiilissasi ei ole vielä käynyt vierailijoita.|Hyväksy kutsu tapaamiseen|Ilmoitukset käytössä|Ilmoitukset pois käytöstä|Poistetaanko tapaaminen?|Anna nimi, maa ja alue|Valitse maa ja alue.',
'da':'Tilbage til chatten|Mødet er ikke tilgængeligt|Du er fjernet fra dette møde|Du deltager ikke i dette møde|Du har accepteret invitationen til mødet|Vil du virkelig fjerne denne person?|Fjern deltager|Skriv til arrangøren|Om mødet|Arrangør|Ingen matcher disse filtre endnu|Ingen har besøgt din profil endnu.|Accepter invitationen til mødet|Notifikationer slået til|Notifikationer slået fra|Slet mødet?|Angiv navn, land og region|Vælg land og region.',
'nl':'Terug naar de chat|Ontmoeting niet beschikbaar|Je bent verwijderd uit deze ontmoeting|Je neemt niet deel aan deze ontmoeting|Je hebt de uitnodiging voor de ontmoeting geaccepteerd|Wil je deze persoon echt verwijderen?|Deelnemer verwijderen|Organisator een bericht sturen|Over de ontmoeting|Organisator|Er past nog niemand bij deze filters|Niemand heeft je profiel nog bezocht.|Uitnodiging voor de ontmoeting accepteren|Meldingen aan|Meldingen uit|Ontmoeting verwijderen?|Vul een naam, land en regio in|Selecteer een land en regio.',
'is':'Til baka í spjall|Samkoman er ekki tiltæk|Þú varst fjarlægður úr þessari samkomu|Þú tekur ekki þátt í þessari samkomu|Þú hefur samþykkt boðið á samkomuna|Viltu örugglega fjarlægja þennan þátttakanda?|Fjarlægja þátttakanda|Skrifa skipuleggjanda|Um samkomuna|Skipuleggjandi|Enginn passar við þessar síur enn|Enginn hefur heimsótt prófílinn þinn enn.|Samþykkja boð á samkomu|Kveikt á tilkynningum|Slökkt á tilkynningum|Eyða samkomu?|Sláðu inn heiti, land og svæði|Veldu land og svæði.'})
batch('Напишите в поддержку и укажите имя профиля и причину жалобы.|Не удалось восстановить изменение участия. Повторите проверку.|Не удалось сменить пароль. Для этого может потребоваться повторный вход.|Не удалось удалить профиль. Проверьте пароль и подключение.|Подтверждение ещё не получено. Проверьте результат без повторной отправки.|Не удалось открыть чат. Попробуйте ещё раз.',{
'en':'Contact support with the profile name and your reason for reporting it.|The membership change could not be restored. Check again.|The password could not be changed. You may need to sign in again.|The profile could not be deleted. Check your password and connection.|Confirmation is still pending. Check the result without sending again.|The chat could not be opened. Try again.',
'de':'Schreiben Sie dem Support und nennen Sie den Profilnamen und den Grund Ihrer Meldung.|Die Änderung der Teilnahme konnte nicht wiederhergestellt werden. Prüfen Sie erneut.|Das Passwort konnte nicht geändert werden. Möglicherweise müssen Sie sich erneut anmelden.|Das Profil konnte nicht gelöscht werden. Prüfen Sie Ihr Passwort und die Verbindung.|Die Bestätigung steht noch aus. Prüfen Sie das Ergebnis, ohne erneut zu senden.|Der Chat konnte nicht geöffnet werden. Versuchen Sie es erneut.',
'es':'Contacta con soporte e indica el nombre del perfil y el motivo de la denuncia.|No se pudo recuperar el cambio de participación. Vuelve a comprobarlo.|No se pudo cambiar la contraseña. Puede que debas volver a iniciar sesión.|No se pudo eliminar el perfil. Comprueba la contraseña y la conexión.|Aún no hay confirmación. Comprueba el resultado sin volver a enviar.|No se pudo abrir el chat. Inténtalo de nuevo.',
'fr':'Contactez l’assistance en indiquant le nom du profil et le motif du signalement.|Impossible de récupérer la modification de participation. Vérifiez à nouveau.|Impossible de modifier le mot de passe. Une nouvelle connexion peut être nécessaire.|Impossible de supprimer le profil. Vérifiez votre mot de passe et votre connexion.|La confirmation est toujours en attente. Vérifiez le résultat sans renvoyer la demande.|Impossible d’ouvrir le chat. Réessayez.',
'it':'Contatta l’assistenza indicando il nome del profilo e il motivo della segnalazione.|Impossibile recuperare la modifica della partecipazione. Verifica di nuovo.|Impossibile cambiare la password. Potrebbe essere necessario accedere di nuovo.|Impossibile eliminare il profilo. Controlla la password e la connessione.|La conferma è ancora in attesa. Verifica il risultato senza inviare di nuovo.|Impossibile aprire la chat. Riprova.',
'pt':'Escreva ao suporte informando o nome do perfil e o motivo da denúncia.|Não foi possível recuperar a alteração de participação. Verifique novamente.|Não foi possível alterar a senha. Talvez seja necessário entrar novamente.|Não foi possível excluir o perfil. Verifique a senha e a conexão.|A confirmação ainda está pendente. Verifique o resultado sem enviar novamente.|Não foi possível abrir a conversa. Tente novamente.',
'el':'Επικοινωνήστε με την υποστήριξη αναφέροντας το όνομα του προφίλ και τον λόγο της αναφοράς.|Δεν ήταν δυνατή η ανάκτηση της αλλαγής συμμετοχής. Ελέγξτε ξανά.|Δεν ήταν δυνατή η αλλαγή κωδικού. Ίσως χρειαστεί να συνδεθείτε ξανά.|Δεν ήταν δυνατή η διαγραφή του προφίλ. Ελέγξτε τον κωδικό και τη σύνδεση.|Η επιβεβαίωση εκκρεμεί. Ελέγξτε το αποτέλεσμα χωρίς να στείλετε ξανά.|Δεν ήταν δυνατό το άνοιγμα της συνομιλίας. Δοκιμάστε ξανά.',
'sr':'Пишите подршци и наведите име профила и разлог пријаве.|Промена учешћа није могла да се обнови. Проверите поново.|Лозинка није промењена. Можда је потребно да се поново пријавите.|Профил није обрисан. Проверите лозинку и везу.|Потврда још није стигла. Проверите резултат без поновног слања.|Разговор није могао да се отвори. Покушајте поново.',
'pl':'Napisz do pomocy, podając nazwę profilu i powód zgłoszenia.|Nie udało się przywrócić zmiany uczestnictwa. Sprawdź ponownie.|Nie udało się zmienić hasła. Może być wymagane ponowne logowanie.|Nie udało się usunąć profilu. Sprawdź hasło i połączenie.|Potwierdzenie jeszcze nie nadeszło. Sprawdź wynik bez ponownego wysyłania.|Nie udało się otworzyć czatu. Spróbuj ponownie.',
'sl':'Pišite podpori ter navedite ime profila in razlog prijave.|Spremembe udeležbe ni bilo mogoče obnoviti. Preverite znova.|Gesla ni bilo mogoče spremeniti. Morda se morate znova prijaviti.|Profila ni bilo mogoče izbrisati. Preverite geslo in povezavo.|Potrditev še ni prispela. Preverite rezultat brez ponovnega pošiljanja.|Klepeta ni bilo mogoče odpreti. Poskusite znova.',
'sk':'Napíšte podpore názov profilu a dôvod nahlásenia.|Zmenu účasti sa nepodarilo obnoviť. Skontrolujte znova.|Heslo sa nepodarilo zmeniť. Možno sa musíte znova prihlásiť.|Profil sa nepodarilo odstrániť. Skontrolujte heslo a pripojenie.|Potvrdenie ešte neprišlo. Skontrolujte výsledok bez opätovného odoslania.|Chat sa nepodarilo otvoriť. Skúste znova.',
'cs':'Napište podpoře název profilu a důvod nahlášení.|Změnu účasti se nepodařilo obnovit. Zkontrolujte znovu.|Heslo se nepodařilo změnit. Možná se musíte znovu přihlásit.|Profil se nepodařilo smazat. Zkontrolujte heslo a připojení.|Potvrzení ještě nepřišlo. Zkontrolujte výsledek bez opětovného odeslání.|Chat se nepodařilo otevřít. Zkuste to znovu.',
'bg':'Пишете на поддръжката и посочете името на профила и причината за сигнала.|Промяната на участието не можа да се възстанови. Проверете отново.|Паролата не можа да се промени. Може да се наложи да влезете отново.|Профилът не можа да се изтрие. Проверете паролата и връзката.|Потвърждението още се очаква. Проверете резултата, без да изпращате отново.|Чатът не можа да се отвори. Опитайте отново.',
'ro':'Scrie echipei de asistență și precizează numele profilului și motivul raportării.|Modificarea participării nu a putut fi recuperată. Verifică din nou.|Parola nu a putut fi schimbată. Poate fi necesară o nouă autentificare.|Profilul nu a putut fi șters. Verifică parola și conexiunea.|Confirmarea este încă în așteptare. Verifică rezultatul fără a trimite din nou.|Chatul nu a putut fi deschis. Încearcă din nou.',
'mk':'Пишете до поддршката и наведете го името на профилот и причината за пријавата.|Промената на учеството не можеше да се обнови. Проверете повторно.|Лозинката не можеше да се смени. Можеби треба повторно да се најавите.|Профилот не можеше да се избрише. Проверете ја лозинката и врската.|Потврдата сè уште се чека. Проверете го резултатот без повторно испраќање.|Разговорот не можеше да се отвори. Обидете се повторно.',
'hu':'Írjon az ügyfélszolgálatnak, és adja meg a profil nevét és a bejelentés okát.|Nem sikerült helyreállítani a részvétel módosítását. Ellenőrizze újra.|Nem sikerült módosítani a jelszót. Lehet, hogy újra be kell jelentkeznie.|Nem sikerült törölni a profilt. Ellenőrizze a jelszavát és a kapcsolatot.|A megerősítés még nem érkezett meg. Újraküldés nélkül ellenőrizze az eredményt.|Nem sikerült megnyitni a beszélgetést. Próbálja újra.',
'sv':'Kontakta supporten och ange profilnamnet och skälet till anmälan.|Ändringen av deltagandet kunde inte återställas. Kontrollera igen.|Lösenordet kunde inte ändras. Du kan behöva logga in igen.|Profilen kunde inte tas bort. Kontrollera lösenordet och anslutningen.|Bekräftelse väntas fortfarande. Kontrollera resultatet utan att skicka igen.|Chatten kunde inte öppnas. Försök igen.',
'nb':'Kontakt kundestøtte med profilnavnet og grunnen til rapporteringen.|Endringen i deltakelse kunne ikke gjenopprettes. Sjekk igjen.|Passordet kunne ikke endres. Du må kanskje logge inn igjen.|Profilen kunne ikke slettes. Sjekk passordet og tilkoblingen.|Bekreftelse ventes fortsatt. Sjekk resultatet uten å sende på nytt.|Chatten kunne ikke åpnes. Prøv igjen.',
'fi':'Ota yhteyttä tukeen ja kerro profiilin nimi ja ilmoituksen syy.|Osallistumisen muutosta ei voitu palauttaa. Tarkista uudelleen.|Salasanaa ei voitu vaihtaa. Sinun on ehkä kirjauduttava uudelleen.|Profiilia ei voitu poistaa. Tarkista salasana ja yhteys.|Vahvistusta odotetaan vielä. Tarkista tulos lähettämättä uudelleen.|Keskustelua ei voitu avata. Yritä uudelleen.',
'da':'Kontakt supporten med profilnavnet og årsagen til anmeldelsen.|Ændringen af deltagelsen kunne ikke gendannes. Tjek igen.|Adgangskoden kunne ikke ændres. Du skal muligvis logge ind igen.|Profilen kunne ikke slettes. Tjek adgangskoden og forbindelsen.|Der ventes stadig på bekræftelse. Tjek resultatet uden at sende igen.|Chatten kunne ikke åbnes. Prøv igen.',
'nl':'Schrijf naar de ondersteuning met de profielnaam en de reden voor je melding.|De wijziging in deelname kon niet worden hersteld. Controleer opnieuw.|Het wachtwoord kon niet worden gewijzigd. Je moet mogelijk opnieuw inloggen.|Het profiel kon niet worden verwijderd. Controleer je wachtwoord en verbinding.|De bevestiging is nog niet ontvangen. Controleer het resultaat zonder opnieuw te verzenden.|De chat kon niet worden geopend. Probeer het opnieuw.',
'is':'Hafðu samband við þjónustuver og tilgreindu heiti prófílsins og ástæðu tilkynningarinnar.|Ekki tókst að endurheimta breytingu á þátttöku. Athugaðu aftur.|Ekki tókst að breyta lykilorðinu. Þú gætir þurft að skrá þig inn aftur.|Ekki tókst að eyða prófílnum. Athugaðu lykilorðið og tenginguna.|Enn er beðið eftir staðfestingu. Athugaðu niðurstöðuna án þess að senda aftur.|Ekki tókst að opna spjallið. Reyndu aftur.'})
batch('Профиль скрыт, но удаление аккаунта не завершено. Повторите попытку или обратитесь в поддержку.|Профиль сохранён, но данные входа не обновились. Войдите снова.|Профиль станет недоступен другим пользователям. Для подтверждения введите пароль.|Сеанс изменился. Проверьте результат после входа в исходный аккаунт.|Не удалось отправить сообщение. Текст сохранён; попробуйте ещё раз.',{
'en':'Your profile is hidden, but account deletion is incomplete. Try again or contact support.|Your profile is saved, but sign-in details were not updated. Sign in again.|Your profile will be hidden from other users. Enter your password to confirm.|The session changed. Sign in to the original account to check the result.|The message could not be sent. Your text is preserved; try again.',
'de':'Ihr Profil ist verborgen, aber das Konto wurde nicht vollständig gelöscht. Versuchen Sie es erneut oder kontaktieren Sie den Support.|Ihr Profil wurde gespeichert, aber die Anmeldedaten wurden nicht aktualisiert. Melden Sie sich erneut an.|Ihr Profil wird für andere Nutzer verborgen. Geben Sie zur Bestätigung Ihr Passwort ein.|Die Sitzung hat sich geändert. Melden Sie sich beim ursprünglichen Konto an, um das Ergebnis zu prüfen.|Die Nachricht konnte nicht gesendet werden. Ihr Text bleibt erhalten; versuchen Sie es erneut.',
'es':'Tu perfil está oculto, pero la eliminación de la cuenta no ha terminado. Inténtalo de nuevo o contacta con soporte.|El perfil se ha guardado, pero los datos de acceso no se han actualizado. Vuelve a iniciar sesión.|Tu perfil dejará de estar disponible para otras personas. Introduce la contraseña para confirmar.|La sesión ha cambiado. Inicia sesión en la cuenta original para comprobar el resultado.|No se pudo enviar el mensaje. El texto se conserva; inténtalo de nuevo.',
'fr':'Votre profil est masqué, mais la suppression du compte est incomplète. Réessayez ou contactez l’assistance.|Votre profil est enregistré, mais les données de connexion n’ont pas été mises à jour. Reconnectez-vous.|Votre profil ne sera plus accessible aux autres utilisateurs. Saisissez votre mot de passe pour confirmer.|La session a changé. Connectez-vous au compte d’origine pour vérifier le résultat.|Impossible d’envoyer le message. Votre texte est conservé ; réessayez.',
'it':'Il profilo è nascosto, ma l’eliminazione dell’account non è completa. Riprova o contatta l’assistenza.|Il profilo è salvato, ma i dati di accesso non sono stati aggiornati. Accedi di nuovo.|Il tuo profilo non sarà più visibile agli altri utenti. Inserisci la password per confermare.|La sessione è cambiata. Accedi all’account originale per verificare il risultato.|Impossibile inviare il messaggio. Il testo è conservato; riprova.',
'pt':'Seu perfil está oculto, mas a exclusão da conta não foi concluída. Tente novamente ou contate o suporte.|O perfil foi salvo, mas os dados de acesso não foram atualizados. Entre novamente.|Seu perfil ficará indisponível para outros usuários. Digite a senha para confirmar.|A sessão mudou. Entre na conta original para verificar o resultado.|Não foi possível enviar a mensagem. O texto foi preservado; tente novamente.',
'el':'Το προφίλ σας είναι κρυφό, αλλά η διαγραφή λογαριασμού δεν ολοκληρώθηκε. Δοκιμάστε ξανά ή επικοινωνήστε με την υποστήριξη.|Το προφίλ αποθηκεύτηκε, αλλά τα στοιχεία σύνδεσης δεν ενημερώθηκαν. Συνδεθείτε ξανά.|Το προφίλ σας δεν θα είναι διαθέσιμο σε άλλους χρήστες. Εισαγάγετε τον κωδικό για επιβεβαίωση.|Η συνεδρία άλλαξε. Συνδεθείτε στον αρχικό λογαριασμό για να ελέγξετε το αποτέλεσμα.|Δεν ήταν δυνατή η αποστολή. Το κείμενό σας διατηρήθηκε· δοκιμάστε ξανά.',
'sr':'Профил је сакривен, али брисање налога није завршено. Покушајте поново или контактирајте подршку.|Профил је сачуван, али подаци за пријаву нису ажурирани. Пријавите се поново.|Ваш профил неће бити доступан другим корисницима. Унесите лозинку за потврду.|Сесија се променила. Пријавите се на првобитни налог да проверите резултат.|Порука није послата. Текст је сачуван; покушајте поново.',
'pl':'Profil jest ukryty, ale usuwanie konta nie zostało zakończone. Spróbuj ponownie lub skontaktuj się z pomocą.|Profil zapisano, ale dane logowania nie zostały zaktualizowane. Zaloguj się ponownie.|Twój profil będzie niedostępny dla innych. Wpisz hasło, aby potwierdzić.|Sesja się zmieniła. Zaloguj się na pierwotne konto, aby sprawdzić wynik.|Nie udało się wysłać wiadomości. Tekst zachowano; spróbuj ponownie.',
'sl':'Profil je skrit, vendar brisanje računa ni dokončano. Poskusite znova ali se obrnite na podporo.|Profil je shranjen, vendar prijavni podatki niso posodobljeni. Prijavite se znova.|Vaš profil drugim uporabnikom ne bo dostopen. Za potrditev vnesite geslo.|Seja se je spremenila. Za preverjanje rezultata se prijavite v prvotni račun.|Sporočila ni bilo mogoče poslati. Besedilo je ohranjeno; poskusite znova.',
'sk':'Profil je skrytý, ale odstránenie účtu nie je dokončené. Skúste znova alebo kontaktujte podporu.|Profil je uložený, ale prihlasovacie údaje sa neaktualizovali. Prihláste sa znova.|Váš profil nebude dostupný ostatným používateľom. Na potvrdenie zadajte heslo.|Relácia sa zmenila. Na kontrolu výsledku sa prihláste do pôvodného účtu.|Správu sa nepodarilo odoslať. Text zostal zachovaný; skúste znova.',
'cs':'Profil je skrytý, ale smazání účtu není dokončeno. Zkuste to znovu nebo kontaktujte podporu.|Profil je uložený, ale přihlašovací údaje se neaktualizovaly. Přihlaste se znovu.|Váš profil nebude dostupný ostatním uživatelům. Pro potvrzení zadejte heslo.|Relace se změnila. Pro kontrolu výsledku se přihlaste do původního účtu.|Zprávu se nepodařilo odeslat. Text zůstal zachován; zkuste to znovu.',
'bg':'Профилът е скрит, но изтриването на акаунта не е завършено. Опитайте отново или се свържете с поддръжката.|Профилът е запазен, но данните за вход не са обновени. Влезте отново.|Профилът ви няма да е достъпен за другите потребители. Въведете паролата за потвърждение.|Сесията се промени. Влезте в първоначалния акаунт, за да проверите резултата.|Съобщението не можа да се изпрати. Текстът е запазен; опитайте отново.',
'ro':'Profilul este ascuns, dar ștergerea contului nu este finalizată. Încearcă din nou sau contactează asistența.|Profilul a fost salvat, dar datele de autentificare nu au fost actualizate. Autentifică-te din nou.|Profilul tău nu va mai fi accesibil altor utilizatori. Introdu parola pentru confirmare.|Sesiunea s-a schimbat. Intră în contul inițial pentru a verifica rezultatul.|Mesajul nu a putut fi trimis. Textul este păstrat; încearcă din nou.',
'mk':'Профилот е скриен, но бришењето на сметката не е завршено. Обидете се повторно или контактирајте ја поддршката.|Профилот е зачуван, но податоците за најава не се ажурирани. Најавете се повторно.|Вашиот профил нема да биде достапен за другите корисници. Внесете ја лозинката за потврда.|Сесијата се промени. Најавете се на првичната сметка за да го проверите резултатот.|Пораката не можеше да се испрати. Текстот е зачуван; обидете се повторно.',
'hu':'A profil rejtve van, de a fiók törlése még nem fejeződött be. Próbálja újra, vagy keresse az ügyfélszolgálatot.|A profil mentve, de a bejelentkezési adatok nem frissültek. Jelentkezzen be újra.|A profilja nem lesz elérhető mások számára. A megerősítéshez adja meg a jelszavát.|A munkamenet megváltozott. Az eredmény ellenőrzéséhez jelentkezzen be az eredeti fiókba.|Az üzenetet nem sikerült elküldeni. A szöveg megmaradt; próbálja újra.',
'sv':'Profilen är dold, men kontot är inte helt borttaget. Försök igen eller kontakta supporten.|Profilen är sparad, men inloggningsuppgifterna uppdaterades inte. Logga in igen.|Din profil blir otillgänglig för andra. Ange lösenordet för att bekräfta.|Sessionen har ändrats. Logga in på det ursprungliga kontot för att kontrollera resultatet.|Meddelandet kunde inte skickas. Texten finns kvar; försök igen.',
'nb':'Profilen er skjult, men kontoen er ikke ferdig slettet. Prøv igjen eller kontakt kundestøtte.|Profilen er lagret, men påloggingsopplysningene ble ikke oppdatert. Logg inn igjen.|Profilen din blir utilgjengelig for andre. Skriv inn passordet for å bekrefte.|Økten har endret seg. Logg inn på den opprinnelige kontoen for å sjekke resultatet.|Meldingen kunne ikke sendes. Teksten er bevart; prøv igjen.',
'fi':'Profiili on piilotettu, mutta tilin poisto on kesken. Yritä uudelleen tai ota yhteyttä tukeen.|Profiili tallennettiin, mutta kirjautumistietoja ei päivitetty. Kirjaudu uudelleen.|Profiilisi ei ole enää muiden nähtävissä. Vahvista syöttämällä salasana.|Istunto vaihtui. Kirjaudu alkuperäiselle tilille tarkistaaksesi tuloksen.|Viestiä ei voitu lähettää. Teksti on säilytetty; yritä uudelleen.',
'da':'Profilen er skjult, men kontoen er ikke færdigslettet. Prøv igen eller kontakt supporten.|Profilen er gemt, men loginoplysningerne blev ikke opdateret. Log ind igen.|Din profil bliver utilgængelig for andre. Indtast adgangskoden for at bekræfte.|Sessionen er ændret. Log ind på den oprindelige konto for at tjekke resultatet.|Beskeden kunne ikke sendes. Teksten er bevaret; prøv igen.',
'nl':'Je profiel is verborgen, maar het account is nog niet volledig verwijderd. Probeer het opnieuw of neem contact op met de ondersteuning.|Je profiel is opgeslagen, maar je inloggegevens zijn niet bijgewerkt. Log opnieuw in.|Je profiel wordt onzichtbaar voor andere gebruikers. Voer je wachtwoord in om te bevestigen.|De sessie is gewijzigd. Log in op het oorspronkelijke account om het resultaat te controleren.|Het bericht kon niet worden verstuurd. De tekst is bewaard; probeer het opnieuw.',
'is':'Prófíllinn er falinn, en eyðingu reikningsins er ekki lokið. Reyndu aftur eða hafðu samband við þjónustuver.|Prófíllinn var vistaður, en innskráningarupplýsingar voru ekki uppfærðar. Skráðu þig inn aftur.|Prófíllinn þinn verður ekki sýnilegur öðrum. Sláðu inn lykilorðið til að staðfesta.|Setan breyttist. Skráðu þig inn á upphaflega reikninginn til að athuga niðurstöðuna.|Ekki tókst að senda skilaboðin. Textinn er varðveittur; reyndu aftur.'})
batch('Не удалось изменить участие. Проверьте соединение.|Не удалось исключить участника. Проверьте соединение.|Не удалось изменить уведомления. Проверьте соединение.',{
'en':'Participation could not be changed. Check your connection.|The participant could not be removed. Check your connection.|Notifications could not be changed. Check your connection.',
'de':'Die Teilnahme konnte nicht geändert werden. Prüfen Sie die Verbindung.|Der Teilnehmer konnte nicht ausgeschlossen werden. Prüfen Sie die Verbindung.|Benachrichtigungen konnten nicht geändert werden. Prüfen Sie die Verbindung.',
'es':'No se pudo cambiar la participación. Comprueba la conexión.|No se pudo excluir al participante. Comprueba la conexión.|No se pudieron cambiar las notificaciones. Comprueba la conexión.',
'fr':'Impossible de modifier la participation. Vérifiez votre connexion.|Impossible d’exclure le participant. Vérifiez votre connexion.|Impossible de modifier les notifications. Vérifiez votre connexion.',
'it':'Impossibile modificare la partecipazione. Controlla la connessione.|Impossibile escludere il partecipante. Controlla la connessione.|Impossibile modificare le notifiche. Controlla la connessione.',
'pt':'Não foi possível alterar a participação. Verifique a conexão.|Não foi possível remover o participante. Verifique a conexão.|Não foi possível alterar as notificações. Verifique a conexão.',
'el':'Δεν ήταν δυνατή η αλλαγή συμμετοχής. Ελέγξτε τη σύνδεση.|Δεν ήταν δυνατή η απομάκρυνση του συμμετέχοντα. Ελέγξτε τη σύνδεση.|Δεν ήταν δυνατή η αλλαγή ειδοποιήσεων. Ελέγξτε τη σύνδεση.',
'sr':'Учешће није промењено. Проверите везу.|Учесник није уклоњен. Проверите везу.|Обавештења нису промењена. Проверите везу.',
'pl':'Nie udało się zmienić uczestnictwa. Sprawdź połączenie.|Nie udało się usunąć uczestnika. Sprawdź połączenie.|Nie udało się zmienić powiadomień. Sprawdź połączenie.',
'sl':'Udeležbe ni bilo mogoče spremeniti. Preverite povezavo.|Udeleženca ni bilo mogoče odstraniti. Preverite povezavo.|Obvestil ni bilo mogoče spremeniti. Preverite povezavo.',
'sk':'Účasť sa nepodarilo zmeniť. Skontrolujte pripojenie.|Účastníka sa nepodarilo odstrániť. Skontrolujte pripojenie.|Upozornenia sa nepodarilo zmeniť. Skontrolujte pripojenie.',
'cs':'Účast se nepodařilo změnit. Zkontrolujte připojení.|Účastníka se nepodařilo odebrat. Zkontrolujte připojení.|Oznámení se nepodařilo změnit. Zkontrolujte připojení.',
'bg':'Участието не можа да се промени. Проверете връзката.|Участникът не можа да се отстрани. Проверете връзката.|Известията не можаха да се променят. Проверете връзката.',
'ro':'Participarea nu a putut fi modificată. Verifică conexiunea.|Participantul nu a putut fi exclus. Verifică conexiunea.|Notificările nu au putut fi modificate. Verifică conexiunea.',
'mk':'Учеството не можеше да се промени. Проверете ја врската.|Учесникот не можеше да се отстрани. Проверете ја врската.|Известувањата не можеа да се променат. Проверете ја врската.',
'hu':'Nem sikerült módosítani a részvételt. Ellenőrizze a kapcsolatot.|Nem sikerült eltávolítani a résztvevőt. Ellenőrizze a kapcsolatot.|Nem sikerült módosítani az értesítéseket. Ellenőrizze a kapcsolatot.',
'sv':'Deltagandet kunde inte ändras. Kontrollera anslutningen.|Deltagaren kunde inte tas bort. Kontrollera anslutningen.|Aviseringarna kunde inte ändras. Kontrollera anslutningen.',
'nb':'Deltakelsen kunne ikke endres. Sjekk tilkoblingen.|Deltakeren kunne ikke fjernes. Sjekk tilkoblingen.|Varslene kunne ikke endres. Sjekk tilkoblingen.',
'fi':'Osallistumista ei voitu muuttaa. Tarkista yhteys.|Osallistujaa ei voitu poistaa. Tarkista yhteys.|Ilmoituksia ei voitu muuttaa. Tarkista yhteys.',
'da':'Deltagelsen kunne ikke ændres. Tjek forbindelsen.|Deltageren kunne ikke fjernes. Tjek forbindelsen.|Notifikationerne kunne ikke ændres. Tjek forbindelsen.',
'nl':'De deelname kon niet worden gewijzigd. Controleer de verbinding.|De deelnemer kon niet worden verwijderd. Controleer de verbinding.|De meldingen konden niet worden gewijzigd. Controleer de verbinding.',
'is':'Ekki tókst að breyta þátttöku. Athugaðu tenginguna.|Ekki tókst að fjarlægja þátttakandann. Athugaðu tenginguna.|Ekki tókst að breyta tilkynningum. Athugaðu tenginguna.'})
batch('Показывать подходящие группы', {
'en':'Show compatible groups','de':'Passende Gruppen anzeigen','es':'Mostrar grupos compatibles','fr':'Afficher les groupes compatibles','it':'Mostra gruppi compatibili','pt':'Mostrar grupos compatíveis','el':'Εμφάνιση συμβατών ομάδων','sr':'Прикажи одговарајуће групе','pl':'Pokaż zgodne grupy','sl':'Pokaži združljive skupine','sk':'Zobraziť kompatibilné skupiny','cs':'Zobrazit kompatibilní skupiny','bg':'Показвай съвместими групи','ro':'Arată grupurile compatibile','mk':'Прикажи соодветни групи','hu':'Összeillő csoportok megjelenítése','sv':'Visa kompatibla grupper','nb':'Vis kompatible grupper','fi':'Näytä yhteensopivat ryhmät','da':'Vis kompatible grupper','nl':'Compatibele groepen tonen','is':'Sýna samhæfa hópa'})
# Equivalent result states have one consistent translated instruction. They all
# retain the same SDK request; the Russian source key remains verbatim.
PENDING='Подтверждение ещё не получено. Проверьте результат без повторной отправки.'
aliases={
 'Результат изменения участия пока неизвестен. Проверьте его перед повтором.':PENDING,
 'Результат открытия чата пока неизвестен. Проверьте результат.':PENDING,
 'Результат отправки пока неизвестен. Проверьте его перед повторной отправкой.':PENDING,
 'Предыдущая операция ожидает подтверждения. Проверьте результат.':PENDING,
}
for code in CODES:
 for key,canonical in aliases.items():OUT[code][key]=key if code=='ru' else OUT[code][canonical]
# These aliases are exact UI synonyms; use the already reviewed translations.
for code in CODES:
 current=json.loads((ROOT/'assets/l10n'/f'{code}.json').read_text())
 for key,canonical in {'Редактировать встречу':'Изменить встречу','Сеанс завершён':'Сеанс завершён. Войдите снова.'}.items():
  OUT[code][key]=key if code=='ru' else current[canonical]
# A re-run may find our previously assembled keys in assets; they must agree.
# Serbian uses the Latn locale throughout the app. This transliteration changes
# display text only; source-language keys and persisted group values stay intact.
def serbian_latin(text):
    source = 'абвгдђежзијклљмнњопрстћуфхцчџш'
    target = ['a','b','v','g','d','đ','e','ž','z','i','j','k','l','lj','m','n','nj','o','p','r','s','t','ć','u','f','h','c','č','dž','š']
    mapping = dict(zip(source, target))
    mapping.update({a.upper(): b.title() for a,b in zip(source,target)})
    return ''.join(mapping.get(char,char) for char in text)
OUT['sr'] = {key: serbian_latin(value) for key,value in OUT['sr'].items()}
(ROOT/'tool/l10n_segments/meetings_profile.json').write_text(json.dumps(OUT,ensure_ascii=False,indent=2)+'\n')
print(len(OUT['ru']),'keys ×',len(CODES),'languages')
