def add_counts(CAT):
    # Each pipe-separated item is participants / age / replies / minutes ago /
    # hours ago / days ago. CLDR selects a form; categories differ by language.
    rows = {
      'ru': {'one':'{count} участник|{count} год|{count} ответ|{count} минуту назад|{count} час назад|{count} день назад', 'few':'{count} участника|{count} года|{count} ответа|{count} минуты назад|{count} часа назад|{count} дня назад', 'many':'{count} участников|{count} лет|{count} ответов|{count} минут назад|{count} часов назад|{count} дней назад', 'other':'{count} участника|{count} года|{count} ответа|{count} минуты назад|{count} часа назад|{count} дня назад'},
      'en': {'one':'{count} participant|{count} year|{count} reply|{count} minute ago|{count} hour ago|{count} day ago', 'other':'{count} participants|{count} years|{count} replies|{count} minutes ago|{count} hours ago|{count} days ago'},
      'de': {'one':'{count} Teilnehmer|{count} Jahr|{count} Antwort|vor {count} Minute|vor {count} Stunde|vor {count} Tag', 'other':'{count} Teilnehmer|{count} Jahre|{count} Antworten|vor {count} Minuten|vor {count} Stunden|vor {count} Tagen'},
      'es': {'one':'{count} participante|{count} año|{count} respuesta|hace {count} minuto|hace {count} hora|hace {count} día', 'other':'{count} participantes|{count} años|{count} respuestas|hace {count} minutos|hace {count} horas|hace {count} días'},
      'fr': {'one':'{count} participant|{count} an|{count} réponse|il y a {count} minute|il y a {count} heure|il y a {count} jour', 'other':'{count} participants|{count} ans|{count} réponses|il y a {count} minutes|il y a {count} heures|il y a {count} jours'},
      'it': {'one':'{count} partecipante|{count} anno|{count} risposta|{count} minuto fa|{count} ora fa|{count} giorno fa', 'other':'{count} partecipanti|{count} anni|{count} risposte|{count} minuti fa|{count} ore fa|{count} giorni fa'},
      'pt': {'one':'{count} participante|{count} ano|{count} resposta|há {count} minuto|há {count} hora|há {count} dia', 'other':'{count} participantes|{count} anos|{count} respostas|há {count} minutos|há {count} horas|há {count} dias'},
      'el': {'one':'{count} συμμετέχων|{count} έτος|{count} απάντηση|πριν από {count} λεπτό|πριν από {count} ώρα|πριν από {count} ημέρα', 'other':'{count} συμμετέχοντες|{count} έτη|{count} απαντήσεις|πριν από {count} λεπτά|πριν από {count} ώρες|πριν από {count} ημέρες'},
      'sr': {'one':'{count} učesnik|{count} godina|{count} odgovor|pre {count} minut|pre {count} sat|pre {count} dan', 'few':'{count} učesnika|{count} godine|{count} odgovora|pre {count} minuta|pre {count} sata|pre {count} dana', 'other':'{count} učesnika|{count} godina|{count} odgovora|pre {count} minuta|pre {count} sati|pre {count} dana'},
      'pl': {'one':'{count} uczestnik|{count} rok|{count} odpowiedź|{count} minutę temu|{count} godzinę temu|{count} dzień temu', 'few':'{count} uczestników|{count} lata|{count} odpowiedzi|{count} minuty temu|{count} godziny temu|{count} dni temu', 'many':'{count} uczestników|{count} lat|{count} odpowiedzi|{count} minut temu|{count} godzin temu|{count} dni temu', 'other':'{count} uczestnika|{count} roku|{count} odpowiedzi|{count} minuty temu|{count} godziny temu|{count} dnia temu'},
      'sl': {'one':'{count} udeleženec|{count} leto|{count} odgovor|pred {count} minuto|pred {count} uro|pred {count} dnevom', 'two':'{count} udeleženca|{count} leti|{count} odgovora|pred {count} minutama|pred {count} urama|pred {count} dnevoma', 'few':'{count} udeleženci|{count} leta|{count} odgovori|pred {count} minutami|pred {count} urami|pred {count} dnevi', 'other':'{count} udeležencev|{count} let|{count} odgovorov|pred {count} minutami|pred {count} urami|pred {count} dnevi'},
      'sk': {'one':'{count} účastník|{count} rok|{count} odpoveď|pred {count} minútou|pred {count} hodinou|pred {count} dňom', 'few':'{count} účastníci|{count} roky|{count} odpovede|pred {count} minútami|pred {count} hodinami|pred {count} dňami', 'many':'{count} účastníka|{count} roka|{count} odpovede|pred {count} minúty|pred {count} hodiny|pred {count} dňa', 'other':'{count} účastníkov|{count} rokov|{count} odpovedí|pred {count} minútami|pred {count} hodinami|pred {count} dňami'},
      'cs': {'one':'{count} účastník|{count} rok|{count} odpověď|před {count} minutou|před {count} hodinou|před {count} dnem', 'few':'{count} účastníci|{count} roky|{count} odpovědi|před {count} minutami|před {count} hodinami|před {count} dny', 'many':'{count} účastníka|{count} roku|{count} odpovědi|před {count} minuty|před {count} hodiny|před {count} dne', 'other':'{count} účastníků|{count} let|{count} odpovědí|před {count} minutami|před {count} hodinami|před {count} dny'},
      'bg': {'one':'{count} участник|{count} година|{count} отговор|преди {count} минута|преди {count} час|преди {count} ден', 'other':'{count} участници|{count} години|{count} отговора|преди {count} минути|преди {count} часа|преди {count} дни'},
      'ro': {'one':'{count} participant|{count} an|{count} răspuns|acum {count} minut|acum {count} oră|acum {count} zi', 'few':'{count} participanți|{count} ani|{count} răspunsuri|acum {count} minute|acum {count} ore|acum {count} zile', 'other':'{count} de participanți|{count} de ani|{count} de răspunsuri|acum {count} de minute|acum {count} de ore|acum {count} de zile'},
      'mk': {'one':'{count} учесник|{count} година|{count} одговор|пред {count} минута|пред {count} час|пред {count} ден', 'other':'{count} учесници|{count} години|{count} одговори|пред {count} минути|пред {count} часа|пред {count} дена'},
      'hu': {'other':'{count} résztvevő|{count} év|{count} válasz|{count} perce|{count} órája|{count} napja'},
      'sv': {'one':'{count} deltagare|{count} år|{count} svar|för {count} minut sedan|för {count} timme sedan|för {count} dag sedan', 'other':'{count} deltagare|{count} år|{count} svar|för {count} minuter sedan|för {count} timmar sedan|för {count} dagar sedan'},
      'nb': {'one':'{count} deltaker|{count} år|{count} svar|for {count} minutt siden|for {count} time siden|for {count} dag siden', 'other':'{count} deltakere|{count} år|{count} svar|for {count} minutter siden|for {count} timer siden|for {count} dager siden'},
      'fi': {'one':'{count} osallistuja|{count} vuosi|{count} vastaus|{count} minuutti sitten|{count} tunti sitten|{count} päivä sitten', 'other':'{count} osallistujaa|{count} vuotta|{count} vastausta|{count} minuuttia sitten|{count} tuntia sitten|{count} päivää sitten'},
      'da': {'one':'{count} deltager|{count} år|{count} svar|for {count} minut siden|for {count} time siden|for {count} dag siden', 'other':'{count} deltagere|{count} år|{count} svar|for {count} minutter siden|for {count} timer siden|for {count} dage siden'},
      'nl': {'one':'{count} deelnemer|{count} jaar|{count} antwoord|{count} minuut geleden|{count} uur geleden|{count} dag geleden', 'other':'{count} deelnemers|{count} jaar|{count} antwoorden|{count} minuten geleden|{count} uur geleden|{count} dagen geleden'},
      'is': {'one':'{count} þátttakandi|{count} ár|{count} svar|fyrir {count} mínútu|fyrir {count} klukkustund|fyrir {count} degi', 'other':'{count} þátttakendur|{count} ár|{count} svör|fyrir {count} mínútum|fyrir {count} klukkustundum|fyrir {count} dögum'},
    }
    keys = ['{count} участников', '{count} лет', '{count} ответов', '{count} минут назад', '{count} часов назад', '{count} дней назад']
    assert set(rows) == set(CAT)
    for code, categories in rows.items():
        for form, values in categories.items():
            values = values.split('|')
            assert len(values) == len(keys), (code,form)
            for key, value in zip(keys,values):
                CAT[code].setdefault(key,{})[form] = value
